### ISSUE TITLE
No able to set locale

### ISSUE THREAD

**Issue by denStrigo** [Apkawa/react-xdsoft-datetimepicker#1]
Datetimepicker uses only the `ru` localization and it is not possible to change it.

**Comment by Apkawa** [comment]
from https://github.com/xdan/datetimepicker
> !!! The latest version of the options 'lang' obsolete. The language setting is now global. !!!

For you 
```DateTimePicker.setLocale('ru')```

**Comment by j4k3** [comment]
ReferenceError: Can't find variable: DateTimePicker.
